Release v0.21.0
wikimedia/eslint-config-wikimedia pull request #401
Opened 2021-10-26 18:07 UTC by edg2s

2021-10-26 19:44 UTC, jdforrester requested changes
Need to split the changes into new rules / changed rules / etc.

2021-10-27 23:16 UTC, jdforrester commented
Let's re-fresh this and release?

2021-11-08 16:44 UTC, edg2s commented
I think this is ready to go now.

2021-11-08 17:54 UTC, jdforrester approved these changes
Fine.

2021-11-08 17:54 UTC, merged