Introduce new rules from wikimedia/eslint-config-node-services
wikimedia/eslint-config-wikimedia pull request #49
Opened 2017-05-01 13:54 UTC by edg2s

Includes many common sense rules we already follow.

Omits rules that are specific to ES6 or server-side environments.

The following stylistic rules is introduced, but is already
mostly followed in Wikimedia code & CSS:
* no-floating-decimal: .5 -> 0.5

The rule that triggers the most on Wikimedia code is probably:
* no-implicit-globals: var myGlobal -> window.myGlobal

2017-05-01 17:48 UTC, jdforrester approved these changes

2017-05-01 18:15 UTC, edg2s commented
We should remove these rules from node-services as downstream duplicates.

2017-05-01 22:36 UTC, Krinkle requested changes
All good, except the loosening of `no-unused-vars`.

2017-05-01 22:36 UTC, Krinkle commented on .eslintrc.json
> +    "no-catch-shadow": "error",
+1.

This is IE<8 specific, so seems redundant. However, given that general block-level variables don't exist in ES5 (only ES6) this one occurrence of block-level variables is probably confusing if we allow it, so best to keep socially enforced that variable names are unique within the entire function.

2017-05-01 22:36 UTC, Krinkle commented on .eslintrc.json
> +    "no-extend-native": "error",
We used to enforce this with JSHint using `freeze`. Good to have this back!

2017-05-01 22:36 UTC, Krinkle commented on .eslintrc.json
> +    "no-multi-str": "error",
(Just for the record.) This too was previously enforced by JSHint already.

2017-05-01 22:36 UTC, Krinkle commented on .eslintrc.json
> +    "no-unused-vars": [ "error", { "args": "none" } ],
`no-unused-vars` is part of eslint:recommended and already currently enforced without exception. I'm not sure we should loosen it to no longer check unused arguments.

<http://eslint.org/docs/rules/no-unused-vars>

2017-05-02 09:54 UTC, edg2s commented on .eslintrc.json
> +    "no-catch-shadow": "error",
Yes - won't cause an error, but could cause confusion.

2017-05-02 09:57 UTC, edg2s commented on .eslintrc.json
> +    "no-multi-str": "error",
Fixed one occurrence in MW core.

2017-05-02 09:57 UTC, edg2s commented on .eslintrc.json
> +    "no-unused-vars": [ "error", { "args": "none" } ],
Oops.

2017-05-02 09:59 UTC, edg2s commented
Fixed.

2017-05-02 18:57 UTC, Krinkle approved these changes

2017-05-02 18:58 UTC, merged