Require empty line between ES6 class members
wikimedia/eslint-config-wikimedia pull request #508
Opened 2023-06-09 19:46 UTC by MatmaRex

I think this has been a long-standing convention for our ES5 code, and now we can enforce it for ES6 code.

2023-06-09 19:47 UTC, catrope approved these changes

2023-06-09 19:51 UTC, catrope requested changes
The tests fail because an example needs to be added to one of the fixtures files. I suggest adding an example of incorrect code (with an eslint-disable-next-line comment) in tests/fixtures/server/invalid.js

2023-06-09 19:57 UTC, MatmaRex commented
Not sure if that works… I don't have this repo set up locally :)

2023-06-10 23:33 UTC, catrope approved these changes

2023-06-10 23:33 UTC, merged